In [3]:
import numpy as np


In [21]:
#One dimensional numpy array
a=np.array([1,2,3])
print(a)

#print shape which is row x column
print("row and columns of the array",c.shape)
#print dimension of the numpy array
print("dimension of the array",c.ndim)
print("datatype of the array ele",c.dtype)

[1 2 3]
row and columns of the array (1, 3, 3)
dimension of the array 3
datatype of the array ele int64


In [20]:
#Two dimensional numpy array
b=np.array([[1,2,3],[3,2,1]])
print(b)
print("row and columns of the array",b.shape)
print("dimension of the array",b.ndim)
print("datatype of the array ele",c.dtype)

[[1 2 3]
 [3 2 1]]
row and columns of the array (2, 3)
dimension of the array 2
datatype of the array ele int64


In [24]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]],dtype='int16')
print(c)
print("row and columns of the array",c.shape)
print("dimension of the array",c.ndim)
print("datatype of the array ele",c.dtype)
print("size of element",c.itemsize)
print("size of array",c.size)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
row and columns of the array (1, 3, 3)
dimension of the array 3
datatype of the array ele int16
size of element 2
size of array 9


In [35]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)
print("row and columns of the array",d.shape)
print("dimension of the array",d.ndim)
print("datatype of the array ele",d.dtype)
print("size of element",d.itemsize)
print("size of array",d.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
row and columns of the array (2, 2, 2)
dimension of the array 3
datatype of the array ele int64
size of element 8
size of array 8


## Accessing/Updating specific elements,rows,columns

In [25]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
#getting specific elemetn [r,c]
a[1,3]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


10

In [26]:
#getting a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6])

In [27]:
#getting a specific column
a[:,2]

array([3, 9])

In [28]:
#updating element
a[0,5]=1
print(a)

[[ 1  2  3  4  5  1]
 [ 7  8  9 10 11 12]]


## Initializing the elements of array

In [30]:
#Initializing with 2 rows and three columns all zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
#Intializing with 2 rows and three columns all ones
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [34]:
#Init with any other number
np.full((2,2), 999)

array([[999, 999],
       [999, 999]])

In [40]:
#Init with any number using already built shape.
np.full(c.shape,999)

array([[[999, 999, 999],
        [999, 999, 999],
        [999, 999, 999]]])

In [39]:
#Init with any number using already built shape.
np.full_like(c,999)

array([[[999, 999, 999],
        [999, 999, 999],
        [999, 999, 999]]], dtype=int16)

In [44]:
#Init with random numbers
np.random.rand(4,2)

array([[0.51719532, 0.47078611],
       [0.47624409, 0.49855725],
       [0.86838902, 0.28924068],
       [0.19240541, 0.10331828]])

In [45]:
#Init with random numbers using already built shape
np.random.random_sample(c.shape)

array([[[0.33659184, 0.91594466, 0.9280303 ],
        [0.53046999, 0.74167728, 0.26420516],
        [0.24094213, 0.2110357 , 0.87745557]]])

In [57]:
#Init with random numbers (1-10) of integers values
np.random.randint(1,11,size=(3,3))

array([[3, 2, 3],
       [1, 9, 7],
       [5, 6, 5]])

In [58]:
#Init with indentity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
#excercise for combining basic array inits
one_m=np.ones([5,5])
zero_m=np.zeros([3,3])
zero_m[1,1]=9
one_m[1:-1,1:-1]=zero_m
print(one_m)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
## Statstics in numpy

In [75]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
#minimum in rows
np.min(stats,axis=1)

array([1, 4])

In [80]:
#sum of whole array
np.sum(stats)

21

In [82]:
#sum of columns
np.sum(stats,axis=0)

array([5, 7, 9])

In [84]:
#sum of rows
np.sum(stats,axis=1)

array([ 6, 15])